### ISSUE TITLE
Python 3.11 compatibility

### ISSUE THREAD

**Issue by muety** [CommonRoad/commonroad-drivability-checker#2]
When trying to install in a Python 3.11 environment, compilation fails.

<details>
<summary>Log</summary>

```
Running setup.py install for commonroad-drivability-checker ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for commonroad-drivability-checker did not run successfully.
  │ exit code: 1
  ╰─> [494 lines of output]
      /tmp/crime/venv/lib/python3.11/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running install
      /tmp/crime/venv/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/commonroad_dc
      copying commonroad_dc/__version__.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc
      copying commonroad_dc/__init__.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc
      running egg_info
      writing commonroad_drivability_checker.egg-info/PKG-INFO
      writing dependency_links to commonroad_drivability_checker.egg-info/dependency_links.txt
      writing requirements to commonroad_drivability_checker.egg-info/requires.txt
      writing top-level names to commonroad_drivability_checker.egg-info/top_level.txt
      reading manifest file 'commonroad_drivability_checker.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'commonroad_drivability_checker.egg-info/SOURCES.txt'
      /tmp/crime/venv/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'commonroad_dc.__pycache__' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'commonroad_dc.__pycache__' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'commonroad_dc.__pycache__' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'commonroad_dc.__pycache__' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/crime/venv/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'commonroad_dc.boundary' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'commonroad_dc.boundary' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'commonroad_dc.boundary' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'commonroad_dc.boundary' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/crime/venv/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'commonroad_dc.collision' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'commonroad_dc.collision' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'commonroad_dc.collision' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'commonroad_dc.collision' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/crime/venv/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'commonroad_dc.collision.collision_detection' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'commonroad_dc.collision.collision_detection' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'commonroad_dc.collision.collision_detection' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'commonroad_dc.collision.collision_detection' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/crime/venv/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'commonroad_dc.collision.trajectory_queries' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'commonroad_dc.collision.trajectory_queries' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'commonroad_dc.collision.trajectory_queries' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'commonroad_dc.collision.trajectory_queries' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/crime/venv/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'commonroad_dc.collision.visualization' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'commonroad_dc.collision.visualization' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'commonroad_dc.collision.visualization' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'commonroad_dc.collision.visualization' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/crime/venv/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'commonroad_dc.costs' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'commonroad_dc.costs' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'commonroad_dc.costs' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'commonroad_dc.costs' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/crime/venv/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'commonroad_dc.feasibility' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'commonroad_dc.feasibility' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'commonroad_dc.feasibility' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'commonroad_dc.feasibility' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/crime/venv/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'commonroad_dc.geometry' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'commonroad_dc.geometry' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'commonroad_dc.geometry' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'commonroad_dc.geometry' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      creating build/lib.linux-x86_64-cpython-311/commonroad_dc/__pycache__
      copying commonroad_dc/__pycache__/__init__.cpython-311.pyc -> build/lib.linux-x86_64-cpython-311/commonroad_dc/__pycache__
      copying commonroad_dc/__pycache__/__init__.cpython-39.pyc -> build/lib.linux-x86_64-cpython-311/commonroad_dc/__pycache__
      copying commonroad_dc/__pycache__/__version__.cpython-311.pyc -> build/lib.linux-x86_64-cpython-311/commonroad_dc/__pycache__
      copying commonroad_dc/__pycache__/__version__.cpython-39.pyc -> build/lib.linux-x86_64-cpython-311/commonroad_dc/__pycache__
      creating build/lib.linux-x86_64-cpython-311/commonroad_dc/boundary
      copying commonroad_dc/boundary/__init__.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/boundary
      copying commonroad_dc/boundary/boundary.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/boundary
      copying commonroad_dc/boundary/construction.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/boundary
      copying commonroad_dc/boundary/lanelet_bounds.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/boundary
      copying commonroad_dc/boundary/rectangle_builder.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/boundary
      copying commonroad_dc/boundary/scenario_bounds.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/boundary
      copying commonroad_dc/boundary/triangle_builder.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/boundary
      creating build/lib.linux-x86_64-cpython-311/commonroad_dc/collision
      copying commonroad_dc/collision/__init__.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/collision
      creating build/lib.linux-x86_64-cpython-311/commonroad_dc/collision/collision_detection
      copying commonroad_dc/collision/collision_detection/__init__.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/collision/collision_detection
      copying commonroad_dc/collision/collision_detection/minkowski_sum.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/collision/collision_detection
      copying commonroad_dc/collision/collision_detection/pycrcc_collision_dispatch.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/collision/collision_detection
      copying commonroad_dc/collision/collision_detection/scenario.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/collision/collision_detection
      creating build/lib.linux-x86_64-cpython-311/commonroad_dc/collision/trajectory_queries
      copying commonroad_dc/collision/trajectory_queries/trajectory_queries.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/collision/trajectory_queries
      copying commonroad_dc/collision/trajectory_queries/trajectory_queries_specialized.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/collision/trajectory_queries
      creating build/lib.linux-x86_64-cpython-311/commonroad_dc/collision/visualization
      copying commonroad_dc/collision/visualization/__init__.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/collision/visualization
      copying commonroad_dc/collision/visualization/drawing.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/collision/visualization
      creating build/lib.linux-x86_64-cpython-311/commonroad_dc/costs
      copying commonroad_dc/costs/__init__.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/costs
      copying commonroad_dc/costs/evaluation.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/costs
      copying commonroad_dc/costs/partial_cost_functions.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/costs
      copying commonroad_dc/costs/route_matcher.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/costs
      creating build/lib.linux-x86_64-cpython-311/commonroad_dc/feasibility
      copying commonroad_dc/feasibility/__init__.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/feasibility
      copying commonroad_dc/feasibility/feasibility_checker.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/feasibility
      copying commonroad_dc/feasibility/solution_checker.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/feasibility
      copying commonroad_dc/feasibility/vehicle_dynamics.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/feasibility
      creating build/lib.linux-x86_64-cpython-311/commonroad_dc/geometry
      copying commonroad_dc/geometry/__init__.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/geometry
      copying commonroad_dc/geometry/geometry.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/geometry
      copying commonroad_dc/geometry/lanelet_ccosy.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/geometry
      copying commonroad_dc/geometry/util.py -> build/lib.linux-x86_64-cpython-311/commonroad_dc/geometry
      running build_ext
      ['-DPYTHON_INCLUDE_DIR=/home/ferdinand/.asdf/installs/python/3.11.3/include/python3.11', '-DPYTHON_LIBRARY=', '-DPYTHON_EXECUTABLE=/tmp/crime/venv/bin/python', '-DBUILD_DOC=OFF', '-DADD_TESTS=OFF', '-DADD_TRIANGLE=OFF', '-DADD_PYTHON_BINDINGS=ON']
      CMake Warning (dev) at CMakeLists.txt:1 (project):
        cmake_minimum_required() should be called prior to this top-level project()
        call.  Please see the cmake-commands(7) manual for usage documentation of
        both commands.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- The C compiler identification is GNU 13.2.0
      -- The CXX compiler identification is GNU 13.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- PYTHON MODE - assuming we are invoked by pip/setup.py
      -- PYTHON MODE - building static libraries
      -- Found Git: /usr/bin/git (found version "2.40.1")
      CMake Deprecation Warning at build/temp.linux-x86_64-cpython-311/build/_deps/ccd-src/CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- Performing Test COMPILER_SUPPORTS_VISIBILITY
      -- Performing Test COMPILER_SUPPORTS_VISIBILITY - Success
      CMake Deprecation Warning at build/temp.linux-x86_64-cpython-311/build/_deps/fcl-src/CMakeLists.txt:39 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- Set RPATH explicitly to '/tmp/pip-install-xer64b0w/commonroad-drivability-checker_b1af0f674b59415e8b49ebaf49f79006/build/temp.linux-x86_64-cpython-311/dist/lib'
      -- FCL does not use OctoMap (as requested)
      -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
      -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
      -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
      -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
      -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
      -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
      CMake Deprecation Warning at build/temp.linux-x86_64-cpython-311/build/_deps/pybind11-src/CMakeLists.txt:8 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- pybind11 v2.6.2
      CMake Warning (dev) at build/temp.linux-x86_64-cpython-311/build/_deps/pybind11-src/tools/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.
      
      Call Stack (most recent call first):
        build/temp.linux-x86_64-cpython-311/build/_deps/pybind11-src/tools/pybind11Tools.cmake:45 (find_package)
        build/temp.linux-x86_64-cpython-311/build/_deps/pybind11-src/tools/pybind11Common.cmake:201 (include)
        build/temp.linux-x86_64-cpython-311/build/_deps/pybind11-src/CMakeLists.txt:188 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found PythonInterp: /tmp/crime/venv/bin/python (found version "3.11.3")
      -- Found PythonLibs: python3.11
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- The non-free Triangle library is excluded from build.
      CMake Deprecation Warning at third_party/libs11n/CMakeLists.txt:2 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- Using full rpaths
      --
      -- /home/ferdinand/.asdf/installs/python/3.11.3/include/python3.11
      --
      -- /tmp/crime/venv/bin/python
      -- Found OpenMP_C: -fopenmp (found version "4.5")
      -- Found OpenMP_CXX: -fopenmp (found version "4.5")
      -- Found OpenMP: TRUE (found version "4.5")
      -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0")
      -- Serialization and pickling support have been enabled for crcc
      -- Serialization and pickling support have been enabled for crccosy
      -- /home/ferdinand/.asdf/installs/python/3.11.3/include/python3.11
      -- Configuring done (5.6s)
      CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
      Please set them or make sure they are set and tested correctly in the CMake files:
      /tmp/pip-install-xer64b0w/commonroad-drivability-checker_b1af0f674b59415e8b49ebaf49f79006/build/temp.linux-x86_64-cpython-311/build/_deps/fcl-src/src/EIGEN3_INCLUDE_DIR
         used as include directory in directory /tmp/pip-install-xer64b0w/commonroad-drivability-checker_b1af0f674b59415e8b49ebaf49f79006/build/temp.linux-x86_64-cpython-311/build/_deps/fcl-src/src
      
      CMake Error in build/temp.linux-x86_64-cpython-311/build/_deps/fcl-src/src/CMakeLists.txt:
        Target "fcl" INTERFACE_INCLUDE_DIRECTORIES property contains path:
      
          "/tmp/pip-install-xer64b0w/commonroad-drivability-checker_b1af0f674b59415e8b49ebaf49f79006/build/temp.linux-x86_64-cpython-311/build/_deps/fcl-src/src/EIGEN3_INCLUDE_DIR-NOTFOUND"
      
        which is prefixed in the build directory.
      
      
      CMake Error in build/temp.linux-x86_64-cpython-311/build/_deps/fcl-src/src/CMakeLists.txt:
        Target "fcl" INTERFACE_INCLUDE_DIRECTORIES property contains path:
      
          "/tmp/pip-install-xer64b0w/commonroad-drivability-checker_b1af0f674b59415e8b49ebaf49f79006/build/temp.linux-x86_64-cpython-311/build/_deps/fcl-src/src/EIGEN3_INCLUDE_DIR-NOTFOUND"
      
        which is prefixed in the build directory.Target "fcl"
        INTERFACE_INCLUDE_DIRECTORIES property contains path:
      
          "/tmp/pip-install-xer64b0w/commonroad-drivability-checker_b1af0f674b59415e8b49ebaf49f79006/build/temp.linux-x86_64-cpython-311/build/_deps/fcl-src/src/EIGEN3_INCLUDE_DIR-NOTFOUND"
      
        which is prefixed in the source directory.
      
      
      CMake Error at cpp/collision/CMakeLists.txt:108 (target_link_libraries):
        Target "crcc" links to:
      
          Eigen3::Eigen
      
        but the target was not found.  Possible reasons include:
      
          * There is a typo in the target name.
          * A find_package call is missing for an IMPORTED target.
          * An ALIAS target is missing.
      
      Call Stack (most recent call first):
        cpp/CMakeLists.txt:182 (include)
      
      
      CMake Error at cpp/geometry/CMakeLists.txt:21 (target_link_libraries):
        Target "crccosy" links to:
      
          Eigen3::Eigen
      
        but the target was not found.  Possible reasons include:
      
          * There is a typo in the target name.
          * A find_package call is missing for an IMPORTED target.
          * An ALIAS target is missing.
      
      Call Stack (most recent call first):
        cpp/CMakeLists.txt:198 (include)
      
      
      -- Generating done (0.0s)
      CMake Generate step failed.  Build files cannot be regenerated correctly.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xer64b0w/commonroad-drivability-checker_b1af0f674b59415e8b49ebaf49f79006/setup.py", line 178, in <module>
          setup(
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/crime/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-xer64b0w/commonroad-drivability-checker_b1af0f674b59415e8b49ebaf49f79006/setup.py", line 44, in run
          self.build_extension(ext)
        File "/tmp/pip-install-xer64b0w/commonroad-drivability-checker_b1af0f674b59415e8b49ebaf49f79006/setup.py", line 139, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=build_dir)
        File "/home/ferdinand/.asdf/installs/python/3.11.3/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-xer64b0w/commonroad-drivability-checker_b1af0f674b59415e8b49ebaf49f79006', '-DPYTHON_INCLUDE_DIR=/home/ferdinand/.asdf/installs/python/3.11.3/include/python3.11', '-DPYTHON_LIBRARY=', '-DPYTHON_EXECUTABLE=/tmp/crime/venv/bin/python', '-DBUILD_DOC=OFF', '-DADD_TESTS=OFF', '-DADD_TRIANGLE=OFF', '-DADD_PYTHON_BINDINGS=ON', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-xer64b0w/commonroad-drivability-checker_b1af0f674b59415e8b49ebaf49f79006/build/temp.linux-x86_64-cpython-311/dist']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> commonroad-drivability-checker
```

</details>

Would be cool to get this fixed or, even better, have a pre-packaged Python 3.11 release.

**Comment by smaierhofer** [comment]
We currently only support Python 3.8-3.10. We will provide Python wheels for newer versions with the next release.

**Comment by geraldfw** [comment]
Hi, yes we were planning to update CR-DC this week and provide a wheel for Python 3.11

**Comment by geraldfw** [comment]
Hi @muety , there is now a PyPi wheel for CR-DC for Python 3.11.
